/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.Airline;
import Business.Airliner;
import Business.AirlineDirectory;
import Business.Fleet;
import Business.FleetDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Girija Dhawale
 */
public class AddFleet extends javax.swing.JPanel {

    /**
     * Creates new form AddFleet
     */
    private FleetDirectory fleetDirectory;
    private JPanel CardSequenceJPanel;
    private Airliner airliner;
    private AirlineDirectory airlineDirectory;      
  

    AddFleet(JPanel CardSequenceJPanel, Airliner airliner, FleetDirectory fleetDirectory,AirlineDirectory airlineDirectory) {
        initComponents();
        this.airliner=airliner;
        this.CardSequenceJPanel=CardSequenceJPanel;
        this.fleetDirectory=fleetDirectory;
        txtAirlinerName.setText(airliner.getAirlineName());
        this.airlineDirectory = airlineDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtAirlinerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSeats = new javax.swing.JTextField();

        setBackground(new java.awt.Color(220, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(new javax.swing.border.MatteBorder(null));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 110, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Add Airplane");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 210, 70));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Airliner");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Model");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 280, 30));

        txtModel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 280, 30));

        txtAirlinerName.setEnabled(false);
        txtAirlinerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlinerNameActionPerformed(evt);
            }
        });
        add(txtAirlinerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 280, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Airline ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Seats");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 50, -1));

        txtSeats.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(txtSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 280, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         String airlineName;
         String a= txtName.getText();
        if("".equals(a)){
            JOptionPane.showMessageDialog(this,"Field name can't be empty");
            return;
        }  
        else{
          airlineName = txtName.getText();
        }
        
         String airlineNo = txtModel.getText();
       try {
            Integer.parseInt(airlineNo);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, airlineNo + " is not a valid number.");
            return;
        }
         String seats= txtSeats.getText();
       try {
            Integer.parseInt(seats);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, seats + " is not a valid number.");
            return;
        }

        Airline airline = new Airline(txtAirlinerName.getText(),airlineName,Integer.parseInt(airlineNo),Integer.parseInt(seats));
        airlineDirectory.addAirliner(airline);
        for(Airline x : airlineDirectory.getAirlineDirectory())
        System.out.println(x.getAirlineName());
        //airD.addAirliner(airline);
        //Fleet fleet = fleetDirectory.addFleet();
//         Fleet fleet =new Fleet();
//            
//        
//        fleet.setAirlinerName(airliner.getAirlineName());
//        String a= txtName.getText();
//        if("".equals(a)){
//         JOptionPane.showMessageDialog(this,"Field name can't be empty");
//         return;
//     }  else{
//          fleet.setName(a);
//         
//     }
//        String b=txtModel.getText();
//         if("".equals(a)){
//         JOptionPane.showMessageDialog(this,"Field name can't be empty");
//         return;
//     }  else{
//            fleet.setModel(b);   
//         }
//        String c= txtSeats.getText();
//       try {
//            Integer.parseInt(c);
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(null, c + " is not a valid number.");
//            return;
//        }
//      
//       fleet.setSeats(Integer.parseInt(c));
//        fleetDirectory.addFleet(fleet);
        JOptionPane.showMessageDialog(null, "Airplane added Successfully");
        txtAirlinerName.setText("");
        txtModel.setText("");
        txtName.setText("");
        txtSeats.setText("");
        
       
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length-1];
        FleetWorkArea FleetWorkAreaJPanel=(FleetWorkArea) component;
        //FleetWorkAreaJPanel.populate();
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAirlinerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlinerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlinerNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSeats;
    // End of variables declaration//GEN-END:variables
}
