/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.AirlineDirectory;
import Business.AirlinerDirectory;
import Business.Airliner;
import Business.FleetDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Girija Dhawale
 */
public class AirlineWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AirlineWorkArea
     */
    
    private JPanel CardSequenceJPanel;
    private AirlineDirectory airdirect;
    private AirlinerDirectory airlinerDirectory;
    private FleetDirectory fleetDirectory;
    

    AirlineWorkArea(JPanel CardSequenceJPanel, AirlineDirectory airDict, AirlinerDirectory airlinerDirectory) {
       initComponents();
       this.CardSequenceJPanel=CardSequenceJPanel;
       this.airdirect=airDict;
       this.airlinerDirectory = airlinerDirectory;
       //this.fleetDirectory=fleetDirectory;
       populatetable();
    }
    
    
    
   public void populatetable(){
       
  int rowCount = tableAirline.getRowCount();
  
   DefaultTableModel dtm = (DefaultTableModel)tableAirline.getModel();
        dtm.setRowCount(0);
        
        for (Airliner a : airlinerDirectory.getAirlinerDirectory()){
            Object[] row = new Object[1];
            row[0] = a.getAirlineName();
            
            dtm.addRow(row);
  
   } 
    
    
   }  
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAirline = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnAddAirline = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnManageFleet = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Manage Airline");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 350, 90));

        tableAirline.setBackground(new java.awt.Color(255, 255, 204));
        tableAirline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableAirline.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        tableAirline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAirline.setGridColor(new java.awt.Color(255, 204, 102));
        tableAirline.setRowHeight(25);
        tableAirline.setSelectionBackground(new java.awt.Color(153, 255, 255));
        tableAirline.setSelectionForeground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(tableAirline);
        if (tableAirline.getColumnModel().getColumnCount() > 0) {
            tableAirline.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 890, 340));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 160, 40));

        btnAddAirline.setBackground(new java.awt.Color(255, 255, 255));
        btnAddAirline.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnAddAirline.setText("Add Airline");
        btnAddAirline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAddAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirlineActionPerformed(evt);
            }
        });
        add(btnAddAirline, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 160, 40));

        btnViewDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnViewDetails.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnViewDetails.setText("View Details");
        btnViewDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 160, 40));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 40));

        btnManageFleet.setBackground(new java.awt.Color(255, 255, 255));
        btnManageFleet.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnManageFleet.setText("Manage Fleet");
        btnManageFleet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnManageFleet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFleetActionPerformed(evt);
            }
        });
        add(btnManageFleet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 160, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirlineActionPerformed
        // TODO add your handling code here:
        AddAirline aa= new AddAirline(CardSequenceJPanel, airdirect, airlinerDirectory);
        CardSequenceJPanel.add(aa);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
        
    }//GEN-LAST:event_btnAddAirlineActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        
        int selectedrow = tableAirline.getSelectedRow();
        if(selectedrow<0){
        JOptionPane.showMessageDialog(null, "Select a row");
        }
        else{
            
        // TODO add your handling code here:
        //Airliner a = (Airliner) tableAirline.getValueAt(selectedrow,0);
        Airliner a = airlinerDirectory.getAirlinerIndex(selectedrow);
        System.out.println(a);
        ViewAirDetails var = new ViewAirDetails(CardSequenceJPanel, a);
        CardSequenceJPanel.add(var);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
                layout.next(CardSequenceJPanel);
        
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedrow= tableAirline.getSelectedRow();
        if(selectedrow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                airlinerDirectory.removeAirliner(selectedrow);
                populatetable();
            }
            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnManageFleetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFleetActionPerformed
        // TODO add your handling code here: 
        int selectRow= tableAirline.getSelectedRow();
        if(selectRow<0)
        {
        JOptionPane.showMessageDialog(null,"Please select an Airliner from the Table!");
        }
        else
        {
        Airliner a = airlinerDirectory.getAirlinerIndex(selectRow);
        FleetWorkArea fleetWork = new FleetWorkArea(CardSequenceJPanel, a, fleetDirectory,airdirect);
        CardSequenceJPanel.add("FleetWorkArea",fleetWork);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);     
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnManageFleetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAirline;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnManageFleet;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAirline;
    // End of variables declaration//GEN-END:variables
}
