/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.Customer;
import Business.CustomerDirectory;
import Business.FlightDetailsDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Girija Dhawale
 */
public class CustomerTADetails extends javax.swing.JPanel {

    /**
     * Creates new form CustomerTADetails
     */
    private JPanel CardSequenceJPanel;
    private CustomerDirectory custDict;
    private FlightDetailsDirectory flightDetailsDirectory;

    CustomerTADetails(JPanel CardSequenceJPanel, CustomerDirectory custDict, FlightDetailsDirectory flightDetailsDirectory) {
       initComponents(); 
       this.CardSequenceJPanel=CardSequenceJPanel;
        this.custDict=custDict;
        this.flightDetailsDirectory = flightDetailsDirectory;
        populate11();
    }
      public void populate11(){
        int rowCount = tableCustomerDetails.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)tableCustomerDetails.getModel();
        dtm.setRowCount(0);
        //for(int i = rowCount-1;i>=0;i--){
        //dtm.removeRow(i);
      //  }
        for (Customer c : custDict.getCustomerDirect()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = c.getBookingId();
            row[1] = c.getFlightNumer();
            row[2] = c.getName();
            row[3] = c.getPhoneNumber();
            row[4] = c.getPassportNumber();
            row[5] = c.getSetSeatNo();
            dtm.addRow(row);
             }
          }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustomerDetails = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(220, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBack.setText("<Back");
        btnBack.setBorder(new javax.swing.border.MatteBorder(null));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 40));

        tableCustomerDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking Id", "Flight Number", "Customer Name", "Phone No", "Passport No", "Customer Seat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCustomerDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 810, 340));

        btnViewDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnViewDetails.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnViewDetails.setText("View Details");
        btnViewDetails.setBorder(new javax.swing.border.MatteBorder(null));
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 150, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("View Booking Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectRow= tableCustomerDetails.getSelectedRow();
        if(selectRow>=0)
        {
          int bookingId = (int) tableCustomerDetails.getValueAt(selectRow,0);
          String flightNo = (String) tableCustomerDetails.getValueAt(selectRow,1);
          ViewCustomerDetails vcd = new ViewCustomerDetails(this.CardSequenceJPanel,bookingId, flightNo, custDict, flightDetailsDirectory);
          CardSequenceJPanel.add("viewcustomerdetails",vcd);
          CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
          layout.next(CardSequenceJPanel);
        
        }
        else{
        JOptionPane.showMessageDialog(null,"Please select a row");
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequenceJPanel.remove(this);
        CardLayout layout=(CardLayout)CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCustomerDetails;
    // End of variables declaration//GEN-END:variables

    
}
