/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.Customer;
import Business.CustomerDirectory;
import Business.FlightDetails;
import Business.FlightDetailsDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.HeadlessException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Girija Dhawale
 */
public class ViewCustomerDetails extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerDetails
     */
     private JPanel CardSequenceJPanel;
    private Customer c;
    private FlightDetails flightDetails;
    private FlightDetailsDirectory flightDetailsDirectory;
    private CustomerDirectory customerDirectory;

    ViewCustomerDetails(JPanel CardSequenceJPanel, int bookingId, String flightNo,CustomerDirectory customerDirectory, FlightDetailsDirectory flightDetailsDirectory) {
        initComponents();
        this.CardSequenceJPanel=CardSequenceJPanel;
        this. flightDetailsDirectory = flightDetailsDirectory;
        this.customerDirectory = customerDirectory;
        for(Customer i: customerDirectory.getCustomerDirect()){
            if(i.getBookingId() == bookingId){
                this.c = i;
            }
        }
        for(FlightDetails f: flightDetailsDirectory.getFlightDetailsDir()){
            System.out.println("checking flight"+ f.getFlightNumber()+" " + flightNo);
            if(f.getFlightNumber() == flightNo){
                this.flightDetails = f;
                System.out.println("Found flight");
            }
        }
        txtName.setText(c.getName());
        txtPhoneNo.setText(c.getPhoneNumber());
        txtPassport.setText(c.getPassportNumber());
        txtFlightNumber.setText(flightDetails.getFlightNumber());
        txtSource.setText(flightDetails.getDeparture());
        txtDeastination.setText(flightDetails.getArrival());
        txtPrice.setText(String.valueOf(flightDetails.getPrice()));
        depDateTextField.setText(flightDetails.getDepartureDate().toLocalDate()+" "+ flightDetails.getDepartureDate().toLocalTime());
        arrivalDateTextField.setText(flightDetails.getArrivalDate().toLocalDate()+" "+ flightDetails.getArrivalDate().toLocalTime());
        airlinerTxtField.setText(flightDetails.getAirliner());
        emailTextField.setText(c.getEmail());
        seatTextField.setText(c.getSetSeatNo());
        
        txtName.setEditable(false);
        txtPhoneNo.setEditable(false);
        txtPassport.setEditable(false);
        txtDeastination.setEditable(false);
        txtSource.setEditable(false);
        txtPrice.setEditable(false);
        txtFlightNumber.setEditable(false);
        depDateTextField.setEditable(false);
        arrivalDateTextField.setEditable(false);
        airlinerTxtField.setEditable(false);
        emailTextField.setEditable(false);
        seatTextField.setEditable(false);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassport = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFlightNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDeastination = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        depDateTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        arrivalDateTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        seatTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        airlinerTxtField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setBackground(new java.awt.Color(51, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.setBorder(new javax.swing.border.MatteBorder(null));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, 42));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 260, 42));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Phone ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, 42));
        add(txtPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 260, 42));

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Passport No");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, 42));
        add(txtPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 260, 42));

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Flight Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, 42));

        txtFlightNumber.setToolTipText("Changes in flight details not allowed from here. In case of change of any details please contact the airliner (Contact details for airliner can be found on their official website)");
        txtFlightNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFlightNumberFocusGained(evt);
            }
        });
        txtFlightNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFlightNumberActionPerformed(evt);
            }
        });
        add(txtFlightNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 260, 42));

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Departure");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, 42));

        txtSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSourceActionPerformed(evt);
            }
        });
        add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 260, 42));

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Arrival");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, 42));
        add(txtDeastination, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 260, 42));

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Price");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, 42));
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 260, 42));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.MatteBorder(null));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 170, 40));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.MatteBorder(null));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 660, 180, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel8.setText("Booking Details");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jLabel9.setText("Departure Date");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, 30));

        depDateTextField.setText("jTextField1");
        add(depDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 260, -1));

        jLabel10.setText("Arrival Date ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, -1, -1));

        arrivalDateTextField.setText("jTextField2");
        add(arrivalDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 260, -1));

        jLabel11.setText("Email");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, -1, -1));

        emailTextField.setText("jTextField1");
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, -1, -1));

        seatTextField.setText("jTextField2");
        seatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatTextFieldActionPerformed(evt);
            }
        });
        add(seatTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, -1, -1));

        jLabel12.setText("Seat");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, -1, -1));

        jLabel13.setText("Airliner");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, -1, -1));

        airlinerTxtField.setText("jTextField3");
        add(airlinerTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("/Users/dhankuwarsisodiya/Downloads/AED_Group_Assignments-TravelAgency/download.png")); // NOI18N
        jLabel14.setText("i");
        jLabel14.setToolTipText("Changes in flight details not allowed from here. In case of change of any details please contact the airliner (Contact details for airliner can be found on their official website)");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 20, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon("/Users/dhankuwarsisodiya/Downloads/AED_Group_Assignments-TravelAgency/download.png")); // NOI18N
        jLabel15.setText("i");
        jLabel15.setToolTipText("Changes in flight details not allowed from here. In case of change of any details please contact the airliner (Contact details for airliner can be found on their official website)");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 20, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon("/Users/dhankuwarsisodiya/Downloads/AED_Group_Assignments-TravelAgency/download.png")); // NOI18N
        jLabel16.setText("i");
        jLabel16.setToolTipText("Changes in flight details not allowed from here. In case of change of any details please contact the airliner (Contact details for airliner can be found on their official website)");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 20, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon("/Users/dhankuwarsisodiya/Downloads/AED_Group_Assignments-TravelAgency/download.png")); // NOI18N
        jLabel17.setText("i");
        jLabel17.setToolTipText("Changes in flight details not allowed from here. In case of change of any details please contact the airliner (Contact details for airliner can be found on their official website)");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 20, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon("/Users/dhankuwarsisodiya/Downloads/AED_Group_Assignments-TravelAgency/download.png")); // NOI18N
        jLabel18.setText("i");
        jLabel18.setToolTipText("Changes in flight details not allowed from here. In case of change of any details please contact the airliner (Contact details for airliner can be found on their official website)");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 20, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon("/Users/dhankuwarsisodiya/Downloads/AED_Group_Assignments-TravelAgency/download.png")); // NOI18N
        jLabel19.setText("i");
        jLabel19.setToolTipText("Changes in flight details not allowed from here. In case of change of any details please contact the airliner (Contact details for airliner can be found on their official website)");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 20, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon("/Users/dhankuwarsisodiya/Downloads/AED_Group_Assignments-TravelAgency/download.png")); // NOI18N
        jLabel20.setText("i");
        jLabel20.setToolTipText("Changes in flight details not allowed from here. In case of change of any details please contact the airliner (Contact details for airliner can be found on their official website)");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, 20, 20));

        jLabel21.setIcon(new javax.swing.ImageIcon("/Users/dhankuwarsisodiya/Downloads/AED_Group_Assignments-TravelAgency/download.png")); // NOI18N
        jLabel21.setText("i");
        jLabel21.setToolTipText("Changes in flight details not allowed from here. In case of change of any details please contact the airliner (Contact details for airliner can be found on their official website)");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 20, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
       txtName.setEditable(true);
        txtPhoneNo.setEditable(true);
        txtPassport.setEditable(true);
        //txtDeastination.setEditable(true);
        //txtSource.setEditable(true);
        //txtPrice.setEditable(true);
        //txtFlightNumber.setEditable(true);
        //depDateTextField.setEditable(true);
        //arrivalDateTextField.setEditable(true);
        //airlinerTxtField.setEditable(true);
        emailTextField.setEditable(true);
        //seatTextField.setEditable(true);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
        String name= txtName.getText().trim();
        String phone=txtPhoneNo.getText().trim();
        String passport=txtPassport.getText().trim();
        String email = emailTextField.getText().trim();
        
        if(!phonePatternCorrect()) {
         JOptionPane.showMessageDialog(CardSequenceJPanel, " Enter valid phone number");
        }else{  
        c.setName(name);
        c.setPhoneNumber(phone);
        c.setPassportNumber(passport);
        c.setEmail(email);
        
        JOptionPane.showMessageDialog(null, "updated successfully");
        }
        txtName.setEditable(false);
        txtPhoneNo.setEditable(false);
        txtPassport.setEditable(false);
        txtDeastination.setEditable(false);
        txtSource.setEditable(false);
        txtPrice.setEditable(false);
        txtFlightNumber.setEditable(false);
        depDateTextField.setEditable(false);
        arrivalDateTextField.setEditable(false);
        airlinerTxtField.setEditable(false);
        emailTextField.setEditable(false);
        seatTextField.setEditable(false);
        }
        catch(HeadlessException | NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Please Enter Correct Data", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFlightNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFlightNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlightNumberActionPerformed

    private void txtSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSourceActionPerformed

    private void seatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatTextFieldActionPerformed

    private void txtFlightNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFlightNumberFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFlightNumberFocusGained
private void backAction() {
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerTADetails cdj = (CustomerTADetails) component;
        cdj.populate11();
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }
boolean phonePatternCorrect()  {
        Pattern p= Pattern.compile("^[0-9]{10}+$");
        Matcher m = p.matcher(txtPhoneNo.getText());
        return m.matches();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerTxtField;
    private javax.swing.JTextField arrivalDateTextField;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField depDateTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField seatTextField;
    private javax.swing.JTextField txtDeastination;
    private javax.swing.JTextField txtFlightNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassport;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
