/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import Business.Customer;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.HeadlessException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Girija Dhawale
 */
public class ViewCustomerDetails extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerDetails
     */
     private JPanel CardSequenceJPanel;
    private Customer c;

    ViewCustomerDetails(JPanel CardSequenceJPanel, Customer c) {
        initComponents();
        this.CardSequenceJPanel=CardSequenceJPanel;
        this.c=c;
        
        txtName.setText(c.getName());
        txtPhoneNo.setText(c.getPhoneNumber());
        txtPassport.setText(c.getPassportNumber());
        //custflighttxt.setText(c.getCustflight());
//        txtFlightNumber.setText(c.getFightNumber());
//        txtSource.setText(c.getDeparture());
//        txtDeastination.setText(c.getArrival());
//        txtPrice.setText(String.valueOf(c.getPrice()));
        //datetxt.setText(c.getDate());
        
        txtName.setEditable(false);
        txtPhoneNo.setEditable(false);
        txtPassport.setEditable(false);
        txtDeastination.setEditable(false);
        txtSource.setEditable(false);
        txtPrice.setEditable(false);
        txtFlightNumber.setEditable(false);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassport = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFlightNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDeastination = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 225, 229));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.setBorder(new javax.swing.border.MatteBorder(null));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, 42));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 260, 42));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Phone ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, 42));
        add(txtPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 260, 42));

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Passport No");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, 42));
        add(txtPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 260, 42));

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Flight Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, 42));
        add(txtFlightNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 260, 42));

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Departure");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, 42));
        add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 260, 42));

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Arrival");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, 42));
        add(txtDeastination, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 260, 42));

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("Price");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, -1, 42));
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 260, 42));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.MatteBorder(null));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 170, 40));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.MatteBorder(null));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 660, 180, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel8.setText("Booking Details");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
       txtName.setEditable(true);
        txtPhoneNo.setEditable(true);
        txtPassport.setEditable(true);
        txtDeastination.setEditable(true);
        txtSource.setEditable(true);
        txtPrice.setEditable(true);
        txtFlightNumber.setEditable(true);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
        String name= txtName.getText().trim();
        String phone=txtPhoneNo.getText().trim();
        String passport=txtPassport.getText().trim();
        
        if(!phonePatternCorrect()) {
         JOptionPane.showMessageDialog(CardSequenceJPanel, " Enter valid phone number");
        }else{  
        c.setName(name);
        c.setPhoneNumber(phone);
        c.setPassportNumber(passport);
        
        JOptionPane.showMessageDialog(null, "updated successfully");
        }
        txtName.setEditable(false);
        txtPhoneNo.setEditable(false);
        txtPassport.setEditable(false);
        txtDeastination.setEditable(false);
        txtSource.setEditable(false);
        txtPrice.setEditable(false);
        txtFlightNumber.setEditable(false);
        }
        catch(HeadlessException | NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Please Enter Correct Data", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_btnBackActionPerformed
private void backAction() {
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerTADetails cdj = (CustomerTADetails) component;
        cdj.populate11();
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }
boolean phonePatternCorrect()  {
        Pattern p= Pattern.compile("^[0-9]{10}+$");
        Matcher m = p.matcher(txtPhoneNo.getText());
        return m.matches();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtDeastination;
    private javax.swing.JTextField txtFlightNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassport;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
