/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import Business.CustomerDirectory;
import Business.AirlineDirectory;
import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Fleet;
import Business.FleetDirectory;
import Business.FlightDetailsDirectory;
import Business.Seats;
import Business.User;
import Business.UserDirectory;
import UserInterface.TravelAgency.ManageAirliner;
import UserInterface.Airliners.LoginAirliner;
import UserInterface.Customer.CustomerSpecification;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Girija Dhawale
 */
public class TravelAgencyMain extends javax.swing.JFrame {

    /**
     * Creates new form TravelAgencyMain
     */
    private AirlineDirectory airDirectory;
    private CustomerDirectory custDirectory;
    private FleetDirectory fleetDirectory;
    private UserDirectory userDirectory;
    private boolean loggedInSession;
    private LoginAirliner lAirliner;
    private AirlinerDirectory airlinerDirectory;
    private Fleet fleet;
    private FlightDetailsDirectory flightDetailsDirectory;
    private Seats seats;
    public TravelAgencyMain() {
        initComponents();
        airDirectory= new AirlineDirectory();
        airlinerDirectory = new AirlinerDirectory();
        custDirectory=new CustomerDirectory();
        fleetDirectory= new FleetDirectory(airDirectory.getAirlineDirectory(),airlinerDirectory.getAirlinerDirectory());
        userDirectory = new UserDirectory();
        flightDetailsDirectory = new FlightDetailsDirectory();
        seats = new Seats();
        fleet = new Fleet(airDirectory.getAirlineDirectory(), airlinerDirectory.getAirlinerDirectory());
        this.loggedInSession = true;
        logoutBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        upperJPanel = new javax.swing.JPanel();
        btnTravelAgency = new javax.swing.JButton();
        btnAirliner = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        CardSequenceJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        upperJPanel.setBackground(new java.awt.Color(149, 165, 166));
        upperJPanel.setPreferredSize(new java.awt.Dimension(1328, 34));

        btnTravelAgency.setBackground(new java.awt.Color(255, 255, 255));
        btnTravelAgency.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnTravelAgency.setText("Travel Agency");
        btnTravelAgency.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTravelAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelAgencyActionPerformed(evt);
            }
        });

        btnAirliner.setBackground(new java.awt.Color(255, 255, 255));
        btnAirliner.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnAirliner.setText("Airline");
        btnAirliner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlinerActionPerformed(evt);
            }
        });

        btnCustomer.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomer.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnCustomer.setText("Customer");
        btnCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upperJPanelLayout = new javax.swing.GroupLayout(upperJPanel);
        upperJPanel.setLayout(upperJPanelLayout);
        upperJPanelLayout.setHorizontalGroup(
            upperJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperJPanelLayout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(btnTravelAgency)
                .addGap(61, 61, 61)
                .addComponent(btnAirliner)
                .addGap(72, 72, 72)
                .addComponent(btnCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(146, 146, 146))
        );
        upperJPanelLayout.setVerticalGroup(
            upperJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(upperJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTravelAgency)
                    .addComponent(btnAirliner)
                    .addComponent(btnCustomer)
                    .addComponent(logoutBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(upperJPanel);

        CardSequenceJPanel.setBackground(new java.awt.Color(255, 255, 255));
        CardSequenceJPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Northeastern Travel Agency ");
        CardSequenceJPanel.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(CardSequenceJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTravelAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelAgencyActionPerformed
        // TODO add your handling code here:
        if(this.loggedInSession){
            ManageAirliner ma = new ManageAirliner(CardSequenceJPanel, custDirectory, airDirectory, fleetDirectory,airlinerDirectory,flightDetailsDirectory);
            CardSequenceJPanel.add(ma);
            CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
            layout.next(CardSequenceJPanel);
        }
        else{
            showLoginDialogue();
        }
    }//GEN-LAST:event_btnTravelAgencyActionPerformed
    public void showLoginDialogue(){
        JTextField username = new JTextField();
            JTextField password = new JPasswordField();
            Object[] message = {
                "Username:", username,
                "Password:", password
            };

            int option = JOptionPane.showConfirmDialog(null, message, "Login", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                String usernameTxt = username.getText();
                String passwordTxt = password.getText();
                System.out.println(userDirectory.getUserDirectory().size());
                for (int i = 0; i < userDirectory.getUserDirectory().size(); i++){
                    if (usernameTxt.equals(userDirectory.getUserDirectory().get(i).getUsername()) && passwordTxt.equals(userDirectory.getUserDirectory().get(i).getPassword())){
                        System.out.println("Login successful");
                        loggedInSession = true;
                        logoutBtn.setVisible(true);
                        ManageAirliner ma = new ManageAirliner(CardSequenceJPanel, custDirectory, airDirectory, fleetDirectory,airlinerDirectory,flightDetailsDirectory);
                        CardSequenceJPanel.add(ma);
                        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
                        layout.next(CardSequenceJPanel);
                            
                    }
                }
                if(!loggedInSession){
                    JOptionPane.showMessageDialog(null,"Wrong Credentials!");
                    showLoginDialogue();
                }
            } else {
                System.out.println("Login canceled");
            }
    }
    private void btnAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlinerActionPerformed
        // TODO add your handling code here:
        if(this.loggedInSession){
          LoginAirliner la = new LoginAirliner(CardSequenceJPanel, airDirectory, fleetDirectory,airlinerDirectory,flightDetailsDirectory);
          lAirliner = la;
        CardSequenceJPanel.add(la);
        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
        }
        else{
            showLoginDialogue();
           System.out.println("Please login to continue"); 
        }
    }//GEN-LAST:event_btnAirlinerActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        CustomerSpecification cs= new CustomerSpecification(CardSequenceJPanel,airDirectory,custDirectory,flightDetailsDirectory,seats);
        CardSequenceJPanel.add("CustomerSpecification",cs);
         CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
        layout.next(CardSequenceJPanel);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        logoutBtn.setVisible(false);
        loggedInSession = false;
        CardSequenceJPanel = new javax.swing.JPanel();
        CardSequenceJPanel.setBackground(new java.awt.Color(255, 255, 255));
        CardSequenceJPanel.setLayout(new java.awt.CardLayout());

        //jLabel1.setIcon(new javax.swing.ImageIcon("/Users/dhankuwarsisodiya/Downloads/airplane.gif")); // NOI18N
        jLabel1.setText("Northeastern Travel Agency ");
        CardSequenceJPanel.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(CardSequenceJPanel);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequenceJPanel;
    private javax.swing.JButton btnAirliner;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnTravelAgency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel upperJPanel;
    // End of variables declaration//GEN-END:variables
}
