/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliners;

import Business.Airline;
import Business.AirlineDirectory;
import Business.Airliner;
import Business.Fleet;
import Business.FleetDirectory;
import Business.FlightDetails;
import Business.FlightDetailsDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.HeadlessException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Girija Dhawale
 */
public class CreateNewAirliner extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirliner
     */
    JPanel CardSequenceJPanel;
    Airliner airliner;
    Fleet fleet;
    FleetDirectory fleetDirectory;
    AirlineDirectory airlineDirectory;
    Airline airline;
    FlightDetailsDirectory flightDetailsDirectory;
    
    public CreateNewAirliner(JPanel CardSequenceJPanel, Airliner airliner, Fleet fleet, AirlineDirectory airlineDirectory, FleetDirectory fleetDirectory ) {
        
    }

    CreateNewAirliner(JPanel CardSequenceJPanel, Airliner airliner, AirlineDirectory airlinerDirectory, Fleet fleet, FleetDirectory fleetDirectory, Airline airline, FlightDetailsDirectory flightDetailsDirectory) {
        initComponents();
        this.CardSequenceJPanel=CardSequenceJPanel;
        this.airliner=airliner;
        this.fleet=fleet;
        this.airlineDirectory=airlinerDirectory;
        this.fleetDirectory=fleetDirectory;
        System.out.println(airliner.getAirlineName());
        this.airline = airline;
        this.flightDetailsDirectory = flightDetailsDirectory;
        
        txtAirliner.setText(airliner.getAirlineName());
        txtAirline.setText(airline.getAirlineName());
        txtAirliner.setEnabled(false);
        txtAirline.setEnabled(false);
    }
private void backAction() {
        CardSequenceJPanel.remove(this);
        Component[] componentArray = CardSequenceJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AirlinerTableDetails atd = (AirlinerTableDetails) component;
       atd.populate1();
        CardLayout layout = (CardLayout) CardSequenceJPanel.getLayout();
        layout.previous(CardSequenceJPanel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFlightNo = new javax.swing.JTextField();
        txtDeparture = new javax.swing.JTextField();
        txtArrival = new javax.swing.JTextField();
        fnolabel = new javax.swing.JLabel();
        sourcelabel = new javax.swing.JLabel();
        destlabel = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        seatlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        pricelabel = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        txtDepDate = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtAirliner = new javax.swing.JTextField();
        txtAirline = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtArrivalDate = new javax.swing.JTextField();
        datelabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 255));

        txtFlightNo.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        txtFlightNo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtFlightNo.setSelectionColor(new java.awt.Color(255, 255, 255));

        txtDeparture.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        txtDeparture.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtDeparture.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtDeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartureActionPerformed(evt);
            }
        });

        txtArrival.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        txtArrival.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtArrival.setSelectionColor(new java.awt.Color(255, 255, 255));

        fnolabel.setBackground(new java.awt.Color(255, 255, 255));
        fnolabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        fnolabel.setText("Flight Number");

        sourcelabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        sourcelabel.setText("Departure");

        destlabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        destlabel.setText("     Arrival");

        backbtn.setBackground(new java.awt.Color(255, 255, 255));
        backbtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        backbtn.setText("<<Back");
        backbtn.setBorder(new javax.swing.border.MatteBorder(null));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        seatlabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        seatlabel.setText("Seats");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create New Flight");

        datelabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        datelabel.setText("Departure Date");

        pricelabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        pricelabel.setText("Price");

        txtPrice.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        txtPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtPrice.setSelectionColor(new java.awt.Color(255, 255, 255));

        addbtn.setBackground(new java.awt.Color(255, 255, 255));
        addbtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        addbtn.setText("Create");
        addbtn.setBorder(new javax.swing.border.MatteBorder(null));
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        txtDepDate.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        txtDepDate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtDepDate.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtDepDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepDateActionPerformed(evt);
            }
        });

        txtSeats.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        txtSeats.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtSeats.setSelectionColor(new java.awt.Color(255, 255, 255));

        txtAirliner.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        txtAirliner.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtAirliner.setSelectionColor(new java.awt.Color(255, 255, 255));

        txtAirline.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        txtAirline.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtAirline.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Airline");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Airliner");

        txtArrivalDate.setFont(new java.awt.Font("SansSerif", 0, 34)); // NOI18N
        txtArrivalDate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtArrivalDate.setSelectionColor(new java.awt.Color(255, 255, 255));

        datelabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        datelabel1.setText("Arrival Date");

        jLabel5.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(338, 338, 338)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(destlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(sourcelabel)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(seatlabel)
                                            .addComponent(datelabel)
                                            .addComponent(jLabel2)
                                            .addComponent(datelabel1)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(121, 121, 121)
                                                .addComponent(jLabel4)
                                                .addGap(0, 66, Short.MAX_VALUE))))
                                    .addGap(39, 39, 39)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtArrivalDate, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                .addComponent(txtAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFlightNo, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                .addComponent(txtAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDeparture, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                .addComponent(txtArrival, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                .addComponent(txtSeats, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                .addComponent(txtDepDate, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(fnolabel)
                            .addGap(421, 421, 421)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(pricelabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(519, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fnolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sourcelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDepDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pricelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:

        backAction();
    }//GEN-LAST:event_backbtnActionPerformed
    
    public static Date parseDate(String date) {
     try {
         return new SimpleDateFormat("yyyy-MM-dd hh:mm:ss").parse(date);
     } catch (ParseException e) {
         return null;
     }
  }
    
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        //if(notxt.getText().isEmpty() || sourcetxt.getText().isEmpty()|| desttxt.getText().isEmpty()||seattxt.getText().isEmpty()||datetxt.getText().isEmpty()||pricetxt.getText().isEmpty()){
            try{
                String number=txtFlightNo.getText().trim();
                String src=txtDeparture.getText().trim();
                String dest=txtArrival.getText().trim();
                int seat=Integer.parseInt(txtSeats.getText().trim());
                String depdateString=txtDepDate.getText().trim();
                String arrivedateString=txtArrivalDate.getText().trim();
                int val=Integer.parseInt(txtPrice.getText().trim());
                
                DateTimeFormatter formatter =  DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                LocalDateTime depdate = LocalDateTime.parse(depdateString, formatter);
                LocalDateTime dateArr = LocalDateTime.parse(arrivedateString, formatter);
                
                   if(!datePatternCorrect()) {
         JOptionPane.showMessageDialog(CardSequenceJPanel, "Date sholud be the form of mm-dd-yyyy");
        }else{   FlightDetails fd = new FlightDetails();   
                fd.setAirlineName(airline.getAirlineName());
                fd.setAirliner(airliner.getAirlineName());
                fd.setFlightNumber(number);
                fd.setDeparture(src);
                fd.setArrival(dest);
                //fd.setSeats(seat);
                fd.setDepartureDate(depdate);
                fd.setArrivalDate(dateArr);
                fd.setPrice(val);
                flightDetailsDirectory.addFlight(fd);

                JOptionPane.showMessageDialog(null, "Airliner successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);
                   }
                txtFlightNo.setText("");
                txtDeparture.setText("");
                txtArrival.setText("");
                txtSeats.setText("");
                txtDepDate.setText("");
                txtPrice.setText("");
                txtArrivalDate.setText("");
            }
            
            catch(HeadlessException | NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Please Enter Correct Data", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_addbtnActionPerformed

    private void txtDepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartureActionPerformed

    private void txtDepDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepDateActionPerformed

     boolean datePatternCorrect()  {
//        Pattern p= Pattern.compile("^(0?[1-9]|1[012])[-]([0-2][0-9]|3[01])[-]([0-9]{4})$");
//        Matcher m = p.matcher(txtDepDate.getText());
//        return m.matches();
         return true;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel datelabel;
    private javax.swing.JLabel datelabel1;
    private javax.swing.JLabel destlabel;
    private javax.swing.JLabel fnolabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel pricelabel;
    private javax.swing.JLabel seatlabel;
    private javax.swing.JLabel sourcelabel;
    private javax.swing.JTextField txtAirline;
    private javax.swing.JTextField txtAirliner;
    private javax.swing.JTextField txtArrival;
    private javax.swing.JTextField txtArrivalDate;
    private javax.swing.JTextField txtDepDate;
    private javax.swing.JTextField txtDeparture;
    private javax.swing.JTextField txtFlightNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSeats;
    // End of variables declaration//GEN-END:variables
}
