/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;
import Business.Airline;
import Business.AirlineDirectory;
import Business.Airliner;
import Business.CustomerDirectory;
import Business.FlightDetails;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Girija Dhawale
 */
public class CustomerSpecification extends javax.swing.JPanel {

    /**
     * Creates new form CustomerSpecification
     */
    private JPanel CardSequenceJPanel;
    private AirlineDirectory airDict;
    private ArrayList<FlightDetails> customerSearch;
    private CustomerDirectory custDict;
    
    public CustomerSpecification(JPanel CardSequenceJPanel, AirlineDirectory airDict,CustomerDirectory custDict) {
        initComponents();
        this.CardSequenceJPanel=CardSequenceJPanel;
        this.airDict=airDict;
        customerSearch= new ArrayList<FlightDetails>();
        this.custDict=custDict;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        btnGo = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 225, 229));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Customer Travel Requirement");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 460, 80));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Departure");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 30));
        add(txtFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 290, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Arrival");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));
        add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 290, 40));

        btnGo.setBackground(new java.awt.Color(255, 255, 255));
        btnGo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnGo.setText("Search");
        btnGo.setBorder(new javax.swing.border.MatteBorder(null));
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        add(btnGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 210, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
//         String src = txtFrom.getText();
//        String destination= txtTo.getText();
//        for(Airline airline : airDict.getAirlineDirectory()){
//        ArrayList<FlightDetails> s= airline.getFlightDetailsDir().getFlightDetailsDir();
//        for(FlightDetails f:s){
//        if(f.getDeparture().equalsIgnoreCase(src) && f.getArrival().equalsIgnoreCase(destination)){
//        customerSearch.add(f);
//                    }
//                }
//        }
//        if(customerSearch.isEmpty()){
//            JOptionPane.showMessageDialog(null,"Flight not found");
//            
//        }
//        else{
//        FlightFilterData ffd = new FlightFilterData(CardSequenceJPanel, customerSearch,custDict);
//        CardSequenceJPanel.add("flightfilterdata",ffd);
//        CardLayout layout = (CardLayout)CardSequenceJPanel.getLayout();
//        layout.next(CardSequenceJPanel);
//        }
        
    }//GEN-LAST:event_btnGoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
